// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBluvxq7-Tt-fLArk86NhBZtsP_Js4yAs0',
    appId: '1:692892755588:web:a6025b46dda6bd435e44d1',
    messagingSenderId: '692892755588',
    projectId: 'pawsenvy-e1eec',
    authDomain: 'pawsenvy-e1eec.firebaseapp.com',
    storageBucket: 'pawsenvy-e1eec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjgFYPxHTrp27meScZiP6Of3VAP30oG5s',
    appId: '1:692892755588:android:fa82080b618b5b545e44d1',
    messagingSenderId: '692892755588',
    projectId: 'pawsenvy-e1eec',
    storageBucket: 'pawsenvy-e1eec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5RE_T90M5Xg3VnU5_C-USlPh36mlfP6A',
    appId: '1:692892755588:ios:5c63ec4b907cdf8c5e44d1',
    messagingSenderId: '692892755588',
    projectId: 'pawsenvy-e1eec',
    storageBucket: 'pawsenvy-e1eec.firebasestorage.app',
    iosClientId: '692892755588-hvj97d74bhjtdis4krvkmv5h99pjc1p7.apps.googleusercontent.com',
    iosBundleId: 'com.example.pawsEnvy',
  );
}
